services:
  database:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_DATABASE: hhplus_concert
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 12341234

    ports:
      - "3308:3306"

  redis:
    container_name: hhplus_redis
    image: redis

    ports:
      - "6380:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    restart: always
    ports:
      - "9982:9982"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper/2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9982, PLAINTEXT_HOST://localhost:9983
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
